#!/usr/bin/env python3
"""Exact first-curvature map on a protected two-shell state, with no output cutoff.

For P=ker T consisting of + modes on |k|=alpha and - modes on |k|=beta,
and a protected background u0 in P, compute

    B = T A_{omega0} |_P,

on every nonzero Fourier output generated by the finite shell convolution.
The only unavoidable kernel direction is omega0, since A_omega0 omega0=0.
This script audits whether extra kernels occur and the nonzero condition ratio
sigma_min(B)^2/sigma_max(B)^2.
"""
import itertools, math
import numpy as np
SQRT2=math.sqrt(2.0)

def canonical(k):
    k=tuple(int(x) for x in k)
    for x in k:
        if x>0:return k,1
        if x<0:return tuple(-y for y in k),-1
    raise ValueError

def hpos(k,s):
    v=np.asarray(k,float); kh=v/np.linalg.norm(v)
    refs=[np.array([1.,0.,0.]),np.array([0.,1.,0.]),np.array([0.,0.,1.])]
    ref=min(refs,key=lambda r:abs(np.dot(r,kh)))
    e1=np.cross(ref,kh); e1/=np.linalg.norm(e1); e2=np.cross(kh,e1)
    return (e1+1j*s*e2)/SQRT2

def h(k,s):
    rep,sgn=canonical(k); hh=hpos(rep,s)
    return hh if sgn>0 else np.conjugate(hh)

def shell(r2):
    rr=int(math.sqrt(r2))
    out=[]
    for k in itertools.product(range(-rr,rr+1),repeat=3):
        if k!=(0,0,0) and sum(x*x for x in k)==r2: out.append(k)
    return sorted(out)

def background(a2,b2,seed,style):
    rng=np.random.default_rng(seed); sa=shell(a2); sb=shell(b2)
    repsa=sorted({canonical(k)[0] for k in sa}); repsb=sorted({canonical(k)[0] for k in sb})
    if style=='sparse': repsa=repsa[:1]; repsb=repsb[:1]
    elif style=='planar':
        pa=[k for k in repsa if k[2]==0]; pb=[k for k in repsb if k[2]==0]
        repsa=pa if pa else repsa[:1]; repsb=pb if pb else repsb[:1]
    def amp():
        if style in ('equal','planar','sparse'):return 1+0j
        if style=='random_phase':return np.exp(1j*rng.uniform(0,2*np.pi))
        return rng.normal()+1j*rng.normal()
    z={}
    for rep in repsa:
        x=amp(); z[(rep,+1)]=x; z[(tuple(-v for v in rep),+1)]=np.conjugate(x)
    for rep in repsb:
        x=amp(); z[(rep,-1)]=x; z[(tuple(-v for v in rep),-1)]=np.conjugate(x)
    n2=sum(abs(x)**2 for x in z.values()); sc=n2**-.5
    return {k:x*sc for k,x in z.items()}

def build_B(a2,b2,seed=11,style='random'):
    alpha=math.sqrt(a2); beta=math.sqrt(b2)
    aa=2*alpha*beta/(alpha+beta); bb=(alpha-beta)/(alpha+beta)
    Pm=[(k,+1) for k in shell(a2)]+[(k,-1) for k in shell(b2)]
    pidx={m:i for i,m in enumerate(Pm)}
    z=background(a2,b2,seed,style)
    omega={}
    for (q,s),amp in z.items(): omega[q]=omega.get(q,np.zeros(3,complex))+s*np.linalg.norm(q)*amp*h(q,s)
    rows={}
    def tval(r,t): return (1-bb*t)*np.linalg.norm(r)-aa
    for col,(p,sp) in enumerate(Pm):
        hp=h(p,sp)
        for q,omq in omega.items():
            r=tuple(p[d]+q[d] for d in range(3))
            if r==(0,0,0):continue
            c=np.cross(hp,omq)
            for t in(-1,+1):
                key=(r,t)
                if key not in rows: rows[key]=np.zeros(len(Pm),complex)
                rows[key][col]+=tval(r,t)*np.vdot(h(r,t),c)
    B=np.vstack(list(rows.values())) if rows else np.zeros((0,len(Pm)),complex)
    wc=np.zeros(len(Pm),complex)
    for (k,s),amp in z.items():
        if (k,s) in pidx: wc[pidx[(k,s)]]=s*np.linalg.norm(k)*amp
    return B,wc,len(Pm),len(rows),len(z)

def stats(B,wc):
    if B.size==0:return 0,0.,0.
    U,s,Vh=np.linalg.svd(B,full_matrices=False)
    tol=max(1e-11,1e-9*s[0]); rank=int(np.sum(s>tol))
    pos=s[:rank]; eta=float((pos[-1]/pos[0])**2) if rank else 0.
    null=Vh[-1,:].conj() if rank<len(Vh) else None
    align=abs(np.vdot(null,wc))/(np.linalg.norm(null)*np.linalg.norm(wc)) if null is not None and np.linalg.norm(wc)>0 else 0.
    return rank,eta,float(align)

def main():
    pairs=[(1,2),(4,5),(5,6),(9,10),(13,14),(17,18),(25,26),(29,30),(34,35),(41,42),(49,50)]
    styles=['random','random_phase','equal','planar','sparse']
    for a2,b2 in pairs:
        if not shell(a2) or not shell(b2):continue
        print(f'--- shells ({a2},{b2}) counts=({len(shell(a2))},{len(shell(b2))}) ---')
        for style in styles:
            seeds=[11,29] if style in ('random','random_phase') else [11]
            for seed in seeds:
                B,wc,p,rows,supp=build_B(a2,b2,seed,style); rank,eta,al=stats(B,wc)
                print(f'{style:12s} seed={seed:2d} P={p:3d} bg={supp:3d} rows={rows:5d} rank={rank:3d}/{p} null={p-rank:2d} eta={eta:.3e} null~omega={al:.6f}')
if __name__=='__main__':main()
